apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app: {{ .Release.Name }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{- range .Values.env }}
  {{- if .valueFrom }}
  {{ .name }}: {{ .valueFrom.secretKeyRef.key | b64enc }}
  {{- end }}
  {{- end }}